create table tb_valores_complementos_cnj (
	cd_valor_complemento integer,
	ds_valor_complemento varchar(200)
)

insert into tb_valores_complementos_cnj values(1,'competência exclusiva');
insert into tb_valores_complementos_cnj values(2,'sorteio');
insert into tb_valores_complementos_cnj values(3,'prevenção');
insert into tb_valores_complementos_cnj values(4,'dependência');
insert into tb_valores_complementos_cnj values(5,'para despacho');
insert into tb_valores_complementos_cnj values(6,'para decisão');
insert into tb_valores_complementos_cnj values(7,'entregue ao destinatário');
insert into tb_valores_complementos_cnj values(8,'não entregue ao destinatário');
insert into tb_valores_complementos_cnj values(9,'designada');
insert into tb_valores_complementos_cnj values(10,'redesignada');
insert into tb_valores_complementos_cnj values(11,'cancelada');
insert into tb_valores_complementos_cnj values(12,'antecipada');
insert into tb_valores_complementos_cnj values(13,'realizada');
insert into tb_valores_complementos_cnj values(14,'não-realizada');
insert into tb_valores_complementos_cnj values(15,'convertida em diligência');
insert into tb_valores_complementos_cnj values(16,'admonitória');
insert into tb_valores_complementos_cnj values(17,'conciliação');
insert into tb_valores_complementos_cnj values(18,'de interrogatório');
insert into tb_valores_complementos_cnj values(19,'de justificação');
insert into tb_valores_complementos_cnj values(20,'em execução');
insert into tb_valores_complementos_cnj values(21,'inicial');
insert into tb_valores_complementos_cnj values(22,'instrução');
insert into tb_valores_complementos_cnj values(23,'instrução e julgamento');
insert into tb_valores_complementos_cnj values(24,'julgamento');
insert into tb_valores_complementos_cnj values(25,'preliminar');
insert into tb_valores_complementos_cnj values(28,'desaforamento');
insert into tb_valores_complementos_cnj values(29,'erro material');
insert into tb_valores_complementos_cnj values(30,'impedimento');
insert into tb_valores_complementos_cnj values(31,'suspeição');
insert into tb_valores_complementos_cnj values(34,'sucessão');
insert into tb_valores_complementos_cnj values(35,'criação de unidade judiciária');
insert into tb_valores_complementos_cnj values(36,'para julgamento');
insert into tb_valores_complementos_cnj values(37,'em diligência');
insert into tb_valores_complementos_cnj values(38,'em grau de recurso');
insert into tb_valores_complementos_cnj values(39,'por devolução ao deprecante');
insert into tb_valores_complementos_cnj values(40,'outros motivos');
insert into tb_valores_complementos_cnj values(41,'Agravo (inominado/ legal)');
insert into tb_valores_complementos_cnj values(42,'Agravo retido');
insert into tb_valores_complementos_cnj values(43,'Alegações finais');
insert into tb_valores_complementos_cnj values(44,'Apelação');
insert into tb_valores_complementos_cnj values(45,'Contestação');
insert into tb_valores_complementos_cnj values(46,'Contra-razões');
insert into tb_valores_complementos_cnj values(47,'Denúncia');
insert into tb_valores_complementos_cnj values(48,'Embargos à ação monitória');
insert into tb_valores_complementos_cnj values(49,'Embargos de declaração');
insert into tb_valores_complementos_cnj values(50,'Embargos infringentes');
insert into tb_valores_complementos_cnj values(51,'Exceção de pré-executividade');
insert into tb_valores_complementos_cnj values(52,'Execução / cumprimento de sentença');
insert into tb_valores_complementos_cnj values(53,'Impugnação ao cumprimento de sentença ');
insert into tb_valores_complementos_cnj values(54,'Impugnação aos embargos');
insert into tb_valores_complementos_cnj values(55,'Memoriais');
insert into tb_valores_complementos_cnj values(56,'Parecer');
insert into tb_valores_complementos_cnj values(57,'Petição (outras)');
insert into tb_valores_complementos_cnj values(58,'Petição inicial');
insert into tb_valores_complementos_cnj values(59,'Razões de apelação criminal');
insert into tb_valores_complementos_cnj values(60,'Razões de recurso em sentido estrito');
insert into tb_valores_complementos_cnj values(61,'Razões finais');
insert into tb_valores_complementos_cnj values(62,'Reconvenção');
insert into tb_valores_complementos_cnj values(63,'Recurso adesivo');
insert into tb_valores_complementos_cnj values(64,'Recurso de sentença (JEF)');
insert into tb_valores_complementos_cnj values(65,'Recurso em sentido estrito');
insert into tb_valores_complementos_cnj values(66,'Recurso especial');
insert into tb_valores_complementos_cnj values(67,'Recurso extraordinário');
insert into tb_valores_complementos_cnj values(68,'Recurso inominado');
insert into tb_valores_complementos_cnj values(69,'Recurso ordinário');
insert into tb_valores_complementos_cnj values(70,'Réplica');
insert into tb_valores_complementos_cnj values(71,'Resposta');
insert into tb_valores_complementos_cnj values(72,'Resposta à acusação');
insert into tb_valores_complementos_cnj values(73,'Alvará');
insert into tb_valores_complementos_cnj values(74,'Aviso de recebimento (AR)');
insert into tb_valores_complementos_cnj values(75,'Carta de ordem');
insert into tb_valores_complementos_cnj values(76,'Carta precatória');
insert into tb_valores_complementos_cnj values(77,'Carta rogatória');
insert into tb_valores_complementos_cnj values(78,'Mandado');
insert into tb_valores_complementos_cnj values(79,'Ofício');
insert into tb_valores_complementos_cnj values(80,'Outros documentos');
insert into tb_valores_complementos_cnj values(81,'Projeto de sentença');
insert into tb_valores_complementos_cnj values(82,'Telegrama');
insert into tb_valores_complementos_cnj values(83,'incompetência');
insert into tb_valores_complementos_cnj values(84,'alteração de competência do órgão');
insert into tb_valores_complementos_cnj values(85,'sorteio manual');
insert into tb_valores_complementos_cnj values(86,'reunião de execuções');
insert into tb_valores_complementos_cnj values(87,'recusa de prevenção/dependência');
insert into tb_valores_complementos_cnj values(88,'remessa de execução cível (CPC, 475-P, par. ún.)');
insert into tb_valores_complementos_cnj values(89,'extinção de unidade judiciária');
insert into tb_valores_complementos_cnj values(90,'declaração de competência para órgão vinculado a Tribunal diferente');
insert into tb_valores_complementos_cnj values(91,'do art. 16 da Lei 11.340');
insert into tb_valores_complementos_cnj values(92,'mediação');
insert into tb_valores_complementos_cnj values(93,'TST');
insert into tb_valores_complementos_cnj values(94,'STJ');
insert into tb_valores_complementos_cnj values(95,'TSE');
insert into tb_valores_complementos_cnj values(97,'adiado o julgamento');
insert into tb_valores_complementos_cnj values(98,'convertido em diligência');
insert into tb_valores_complementos_cnj values(99,'pedido de vista');
insert into tb_valores_complementos_cnj values(100,'retificação de resultado de julgamento');
insert into tb_valores_complementos_cnj values(101,'retirado de pauta');
insert into tb_valores_complementos_cnj values(102,'ratificada a liminar');
insert into tb_valores_complementos_cnj values(103,'não ratificada a liminar');
insert into tb_valores_complementos_cnj values(104,'ratificada parcialmente a liminar');
insert into tb_valores_complementos_cnj values(105,'Controvérsia');
insert into tb_valores_complementos_cnj values(106,'Tema');
insert into tb_valores_complementos_cnj values(107,'Certidão');
insert into tb_valores_complementos_cnj values(108,'cumpridos');
insert into tb_valores_complementos_cnj values(109,'não cumpridos');
insert into tb_valores_complementos_cnj values(110,'cumpridos parcialmente');
insert into tb_valores_complementos_cnj values(111,'Renúncia de mandato');
insert into tb_valores_complementos_cnj values(112,'Procuração/substabelecimento com reserva de poderes');
insert into tb_valores_complementos_cnj values(113,'Procuração/substabelecimento sem reserva de poderes');
insert into tb_valores_complementos_cnj values(114,'Embargos de divergência');
insert into tb_valores_complementos_cnj values(115,'Incidente de uniformização de jurisprudência');
insert into tb_valores_complementos_cnj values(116,'Informações');
insert into tb_valores_complementos_cnj values(117,'Acórdão');
insert into tb_valores_complementos_cnj values(118,'Sentença');
insert into tb_valores_complementos_cnj values(119,'Pedido de Instauração de IRDR');
insert into tb_valores_complementos_cnj values(120,'Pedido de Instauração de IAC');
insert into tb_valores_complementos_cnj values(121,'Parecer \Falta de Interesse\ (MP)');
insert into tb_valores_complementos_cnj values(122,'Parecer de Mérito (MP)');
insert into tb_valores_complementos_cnj values(123,'Parecer sobre a admissibilidade de incidente ou recurso para estabelecer precedente qualificado (MP)');
insert into tb_valores_complementos_cnj values(124,'A mulher');
insert into tb_valores_complementos_cnj values(125,'O idoso');
insert into tb_valores_complementos_cnj values(126,'A criança ou adolescente');
insert into tb_valores_complementos_cnj values(127,'Suspensão da posse ou restrição do porte de armas');
insert into tb_valores_complementos_cnj values(128,'Afastamento do lar ou domicílio');
insert into tb_valores_complementos_cnj values(129,'Proibição de aproximação da ofendida, de seus familiares e das testemunhas');
insert into tb_valores_complementos_cnj values(130,'Proibição de contato com a ofendida, seus familiares e testemunhas por qualquer meio de comunicação');
insert into tb_valores_complementos_cnj values(131,'Proibição de frequentação de determinados lugares');
insert into tb_valores_complementos_cnj values(132,'Proibição de condutas quaisquer, não especificadas pela Lei');
insert into tb_valores_complementos_cnj values(133,'Restrição ou suspensão de visitas aos dependentes menores');
insert into tb_valores_complementos_cnj values(134,'Prestação de alimentos provisionais ou provisórios');
insert into tb_valores_complementos_cnj values(135,'Encaminhamento da ofendida e seus dependentes a programa oficial ou comunitário de proteção ou de atendimento');
insert into tb_valores_complementos_cnj values(136,'Determinação da recondução da ofendida e de seus dependentes ao respectivo domicílio, após o afastamento do agressor');
insert into tb_valores_complementos_cnj values(137,'Determinação do afastamento da ofendida do lar');
insert into tb_valores_complementos_cnj values(138,'Encaminhamento à família, mediante termo de responsabilidade');
insert into tb_valores_complementos_cnj values(139,'Encaminhamento a curador, mediante termo de responsabilidade');
insert into tb_valores_complementos_cnj values(140,'Oreintação, apoio e acompanhamento temporários');
insert into tb_valores_complementos_cnj values(141,'Requisição para tratamento de sua saúde, em regime ambulatorial');
insert into tb_valores_complementos_cnj values(142,'Requisição para tratamento de sua saúde, em regime hospitalar');
insert into tb_valores_complementos_cnj values(143,'Requisção para tratamento de sua saúde, em regime domiciliar');
insert into tb_valores_complementos_cnj values(144,'Inclusão em programa oficial ou comunitário de auxílio, orientação e tratamento a usuários de drogas lícitas ou ilícitas ao próprio idoso');
insert into tb_valores_complementos_cnj values(145,'Inclusão em programa oficial ou comunitário de auxílio, orientação e tratamento a usuários de drogas lícitas ou ilícitas à pessoa de sua convivência que lhe cause perturbação');
insert into tb_valores_complementos_cnj values(146,'Abrigo em entidade');
insert into tb_valores_complementos_cnj values(147,'Abrigo temporário');
insert into tb_valores_complementos_cnj values(148,'Encaminhamento aos pais, mediante termo de responsabilidade');
insert into tb_valores_complementos_cnj values(149,'Encaminhamento ao responsável, mediante termo de responsabilidade');
insert into tb_valores_complementos_cnj values(150,'Matrícula e frequência obrigatórias em estabelecimento oficial de ensino fundamental');
insert into tb_valores_complementos_cnj values(151,'Inclusão em serviços e programas oficiais ou comunitários de proteção, apoio e promoção da família, da criança e do adolescente');
insert into tb_valores_complementos_cnj values(152,'Requisição de tratamento médico, em regime ambulatorial');
insert into tb_valores_complementos_cnj values(153,'Requisição de tratamento médico, em regime hospitalar');
insert into tb_valores_complementos_cnj values(154,'Requisição de tratamento psicológico, em regime ambulatorial');
insert into tb_valores_complementos_cnj values(155,'Requisição de tratamento psicológico, em regime hospitalar');
insert into tb_valores_complementos_cnj values(156,'Requisição de tratamento psiquiátrico, em regime ambulatorial');
insert into tb_valores_complementos_cnj values(157,'Requisção de tratamento psiquiátrico em regime hospitalar');
insert into tb_valores_complementos_cnj values(158,'Inclusão em programa oficial ou comunitário de auxílio, orientação e tratamento a alcóolatras');
insert into tb_valores_complementos_cnj values(159,'Inclusão em programa oficial ou comunitário de auxílio, orientação e tratamento a toxicômanos');
insert into tb_valores_complementos_cnj values(160,'Acolhimento institucional');
insert into tb_valores_complementos_cnj values(161,'Inclusão em programa de acolhimento familiar');
insert into tb_valores_complementos_cnj values(162,'Colocação em família substituta');
insert into tb_valores_complementos_cnj values(163,'Ofício - Descumprimento de Medida Protetiva (Lei Maria da Penha)');
insert into tb_valores_complementos_cnj values(164,'Agravo em recurso extraordinário');
insert into tb_valores_complementos_cnj values(165,'Agravo em recurso especial');
insert into tb_valores_complementos_cnj values(166,'Cadastramento de processos antigos');
insert into tb_valores_complementos_cnj values(167,'Encaminhamento para verificação de prevenção');
insert into tb_valores_complementos_cnj values(168,'Inquérito não distribuído (art. 2º da Resolução CJF 63/2009)');
insert into tb_valores_complementos_cnj values(169,'Retificada a autuação');
insert into tb_valores_complementos_cnj values(170,'Carta');
insert into tb_valores_complementos_cnj values(171,'Despacho de recurso especial como representativo de controvérsia');
insert into tb_valores_complementos_cnj values(172,'Deferimento/Indeferimento de revogação de prisão');
insert into tb_valores_complementos_cnj values(173,'Deferimento/Indeferimento de comutação de pena e/ou progressão de regime');
insert into tb_valores_complementos_cnj values(174,'Deferimento/Indeferimento de Pedido de Liberdade Provisória');
insert into tb_valores_complementos_cnj values(175,'Decisão de prisão preventiva');
insert into tb_valores_complementos_cnj values(176,'Acórdão dos Embargos de Declaração nos Embargos Infringentes');
insert into tb_valores_complementos_cnj values(177,'Tradução Oficial');
insert into tb_valores_complementos_cnj values(178,'Sentença Estrangeira');
insert into tb_valores_complementos_cnj values(179,'Pedido de reconsideração');
insert into tb_valores_complementos_cnj values(180,'Embargos à Execução');
insert into tb_valores_complementos_cnj values(181,'Decisão');
insert into tb_valores_complementos_cnj values(182,'Ato coator');
insert into tb_valores_complementos_cnj values(183,'Auto de prisão em flagrante');
insert into tb_valores_complementos_cnj values(184,'de acolhimento');
insert into tb_valores_complementos_cnj values(185,'Juiz(a)');
insert into tb_valores_complementos_cnj values(186,'Juiz(a) leigo(a)');
insert into tb_valores_complementos_cnj values(187,'Mediador(a)');
insert into tb_valores_complementos_cnj values(188,'Conciliador(a)');
insert into tb_valores_complementos_cnj values(189,'para admissibilidade recursal');
insert into tb_valores_complementos_cnj values(190,'encerradas atribuições CEJUSC');
insert into tb_valores_complementos_cnj values(191,'Pedido de assistência simples');
insert into tb_valores_complementos_cnj values(192,'Pedido de assistência litisconsorcial');
insert into tb_valores_complementos_cnj values(193,'de custódia');
insert into tb_valores_complementos_cnj values(194,'por julgamento definitivo do recurso');
